import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/Link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="ico" sizes="16x16" href="favicon.ico" />
      </Head>

      <Link href="/plan">Plan every second, maintain total flexibility.</Link>

      <footer className={styles.footer}>
        <a
          href="https://"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Space
        </a>
      </footer>
    </div>
  );
}
